### ISSUE TITLE
Not working with laravel 6.2

### ISSUE THREAD

**Issue by Stancobridge** [kaoken/laravel-markdown-it#1]
I tried installing this package on laravel 6.2 but composer keep throwing error during installation

`
Problem 1
- Conclusion: don't install laravel/framework v6.7.0
- Conclusion: remove laravel/framework v6.6.2
- Conclusion: don't install laravel/framework v6.6.2
- Conclusion: don't install laravel/framework v6.6.1
- Conclusion: don't install laravel/framework v6.6.0
- Conclusion: don't install laravel/framework v6.5.2
- Conclusion: don't install laravel/framework v6.5.1
- Conclusion: don't install laravel/framework v6.5.0
- Conclusion: don't install laravel/framework v6.4.1
- Conclusion: don't install laravel/framework v6.4.0
- Conclusion: don't install laravel/framework v6.3.0
- Conclusion: don't install laravel/framework v6.2.0
- kaoken/laravel-markdown-it 1.5.2 requires laravel/framework 5.5. -> satisfiable by laravel/framework[5.5.x-dev].
- kaoken/laravel-markdown-it 1.0.0 requires laravel/framework 5.4. -> satisfiable by laravel/framework[5.4.x-dev].
- kaoken/laravel-markdown-it 1.0.3 requires laravel/framework 5.4.* -> satisfiable by laravel/framework[5.4.x-dev].
- Can only install one of: laravel/framework[6.x-dev, 5.5.x-dev].
- laravel/framework 6.x-dev conflicts with laravel/framework[5.4.x-dev].
- Installation request for laravel/framework ^6.2 -> satisfiable by laravel/framework[6.x-dev, v6.2.0, v6.3.0, v6.4.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0].
- Installation request for kaoken/laravel-markdown-it ^1.0 -> satisfiable by kaoken/laravel-markdown-it[1.0.0, 1.0.3, 1.5.2].
`

**Comment by yasuken2013** [comment]
Sorry for my late reply.

Starting today, Laravel 6.x is also supported.
